// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzmzeahzstxmounpumca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6bXplYWh6c3R4bW91bnB1bWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzM0MTgsImV4cCI6MjA3MjY0OTQxOH0.FMhfp3KPGJ59Yi2LIMjPFvz_51wE2UrThbpVuUaQvAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});